{% set version = "1.1.0" %}

package:
  name: wq.io
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wq.io/wq.io-{{ version }}.tar.gz
  sha256: 23f1ed5712983160b9cef9598f5a789553749ea49665a8bce85b5b51b4c248b5

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - wq.core
    - xlrd
    - fiona

test:
  requires:
    - python {{ python_min }}
  imports:
    - wq
    - wq.io
    - wq.io.gis
    - wq.io.parsers

about:
  home: https://wq.io/wq.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Consistent iterable API for reading and writing to external datasets"

extra:
  recipe-maintainers:
    - ocefpaf
