travis:
  secure:
    BINSTAR_TOKEN: MPOswNi0GqLGtkuUeKvyH+LkX4Esd6BMB9LRTnbZ0fIcNBgbyKc8nf/YVOcKjA14bvC0tQDOZbx/yyKilyTNebbqgRApcnEPNKkHCWk2Eo3YAoZHWIhe6QHNUgHAGUWsNe3e+ToKfCS5q57oj2MFmYgITzPEnBYTHKMiK99xueCt8gLsZtHjae4tg67pdOwJyDzEiB4cfM6BvB+ji/pPpJhwzO6F7ZML8E5+cnFFVPoCe+35FS/ZSoYi6wFF5pMLRGSMPGAz/9+VjaMgqI46Cl6a0e6Mn9l6mU2Pydf3Bc54jud+aYGNsXS/UVePtyMNo19Nho4do861xZ15rkrCe4frpcxgL9uHS1M7T3c7AqrIFIr/IVtL7uOUGIQGVPrdFTtgTYcoMIkhPJ0GjSL5jGMMmStes34/+vapqFM76O4AiEup1amCw6kyx7VIbqrRgr3T5MJD0M6m/jymyECqw3YGbua9ifafbWzeHKE7cRfMJLDKR7/DEFGX96kazwvpdsbJJjBU/fk9BYbmSYIchxVOmNL23gl6p+jDRIN6QazjLmyzSnHiLJXXh9DyS76GWiXnn1s5MAcqQutq9Cb0syBl0DO2Tr9rDjzAMUEBZ4ZBaURKUim3LcTcF77OT7E1DlYrHJwwTivkwlPAfwc8uHUd8ChohClUvX/cVfW3EhE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
