travis:
  secure:
    BINSTAR_TOKEN: TlMuYi5bYw0gpNnOH26g52NegjE+wn0RmuRrx+WGRxRdQ0ThdXyppIU67hzTeTv89er8g9cQF7qJmDuW879pSUD5Ez6/wjYYvAhcrGwhvJQu0KdGCPdF6ya7/XxgauwoL5oJNET9NjG/BSD2Y+gwE9wAsxNgiMD8zUHTMacTjuFjya4JtTg1Y5+JAzN0wSTP8e0o4RFBQxbHU0eAboWqzLk5V1zQQ/vUf6IvPNqiRBMi8dyoOnTpY7PjziXF+apZr0Bf0iX1PLV0bKa5f92tD9dtqh39w1Hy5psatg8oHa+TpoDnZIUCC39SrKj4Ti+Kg6N/BVE9crBFUB8yGPlNozPPSCHgWkGOjLIloJYujylXqOFQr3pnVOfiMbdzvPDNsyOA7Zlzgj2Q6Rtos180PEP68+xPdq/t3lamS+JhmzXPr1U/nX2BSlLgkt77D5g03huk/mQGKO8ap4FuvPg0t8jhg+HViDNE2w736EgxvAOGDK4iyc3Xz4i06JXJVJizyk7LyVbca6nm0BGA7ojC/jHTcm/vLojcqXNLtA9MaMmZxx4w3zAGGw6ohipRJAU72/sbDGefpZ/WEPg1QKWR7vAEZ2HKG1fhlA0HS/IjErXu4Kj4WW+A8cLeRX7yVdw9vEWKyJ0GAsUU1isn7pcW3Ah78RZkjX1/I/Nl25Wx9Kc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
